######################################################################
# Automatically generated by qmake (2.01a) sam. sept. 15 17:24:29 2012
######################################################################

TEMPLATE = app
TARGET = 
DEPENDPATH += .
INCLUDEPATH += .

# Input
HEADERS += GraphicalCore.h
SOURCES += GraphicalCore.cpp main.cpp
