######################################################################
# Automatically generated by qmake (2.01a) sam. sept. 15 23:40:48 2012
######################################################################

TEMPLATE = app
TARGET = 
DEPENDPATH += .
INCLUDEPATH += .

# Input
HEADERS += DigitalNumber.h DigitalTimerDisplay.h GraphicalCore.h
SOURCES += DigitalNumber.cpp DigitalTimerDisplay.cpp GraphicalCore.cpp main.cpp
RESOURCES += resources.qrc
win32:RC_FILE += icon.rc
